//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.8.3928.0.
// 
namespace Gus.Regon.BIR11.Proxy.Models.DanePobierzPelnyRaport.BIR11JednLokalnaOsPrawnej
{
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class root {
        
        private rootDane daneField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public rootDane dane {
            get {
                return this.daneField;
            }
            set {
                this.daneField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class rootDane {
        
        private string lokpraw_regon14Field;
        
        private string lokpraw_nazwaField;
        
        private string lokpraw_numerWrejestrzeEwidencjiField;
        
        private string lokpraw_dataWpisuDoRejestruEwidencjiField;
        
        private string lokpraw_dataPowstaniaField;
        
        private string lokpraw_dataRozpoczeciaDzialalnosciField;
        
        private string lokpraw_dataWpisuDoRegonField;
        
        private string lokpraw_dataZawieszeniaDzialalnosciField;
        
        private string lokpraw_dataWznowieniaDzialalnosciField;
        
        private string lokpraw_dataZaistnieniaZmianyField;
        
        private string lokpraw_dataZakonczeniaDzialalnosciField;
        
        private string lokpraw_dataSkresleniaZRegonField;
        
        private string lokpraw_adSiedzKraj_SymbolField;
        
        private string lokpraw_adSiedzWojewodztwo_SymbolField;
        
        private string lokpraw_adSiedzPowiat_SymbolField;
        
        private string lokpraw_adSiedzGmina_SymbolField;
        
        private string lokpraw_adSiedzKodPocztowyField;
        
        private string lokpraw_adSiedzMiejscowoscPoczty_SymbolField;
        
        private string lokpraw_adSiedzMiejscowosc_SymbolField;
        
        private string lokpraw_adSiedzUlica_SymbolField;
        
        private string lokpraw_adSiedzNumerNieruchomosciField;
        
        private string lokpraw_adSiedzNumerLokaluField;
        
        private string lokpraw_adSiedzNietypoweMiejsceLokalizacjiField;
        
        private string lokpraw_adSiedzKraj_NazwaField;
        
        private string lokpraw_adSiedzWojewodztwo_NazwaField;
        
        private string lokpraw_adSiedzPowiat_NazwaField;
        
        private string lokpraw_adSiedzGmina_NazwaField;
        
        private string lokpraw_adSiedzMiejscowosc_NazwaField;
        
        private string lokpraw_adSiedzMiejscowoscPoczty_NazwaField;
        
        private string lokpraw_adSiedzUlica_NazwaField;
        
        private string lokpraw_formaFinansowania_SymbolField;
        
        private string lokpraw_organRejestrowy_SymbolField;
        
        private string lokpraw_rodzajRejestruEwidencji_SymbolField;
        
        private string lokpraw_formaFinansowania_NazwaField;
        
        private string lokpraw_organRejestrowy_NazwaField;
        
        private string lokpraw_rodzajRejestruEwidencji_NazwaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string lokpraw_regon14 {
            get {
                return this.lokpraw_regon14Field;
            }
            set {
                this.lokpraw_regon14Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string lokpraw_nazwa {
            get {
                return this.lokpraw_nazwaField;
            }
            set {
                this.lokpraw_nazwaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string lokpraw_numerWrejestrzeEwidencji {
            get {
                return this.lokpraw_numerWrejestrzeEwidencjiField;
            }
            set {
                this.lokpraw_numerWrejestrzeEwidencjiField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string lokpraw_dataWpisuDoRejestruEwidencji {
            get {
                return this.lokpraw_dataWpisuDoRejestruEwidencjiField;
            }
            set {
                this.lokpraw_dataWpisuDoRejestruEwidencjiField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string lokpraw_dataPowstania {
            get {
                return this.lokpraw_dataPowstaniaField;
            }
            set {
                this.lokpraw_dataPowstaniaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string lokpraw_dataRozpoczeciaDzialalnosci {
            get {
                return this.lokpraw_dataRozpoczeciaDzialalnosciField;
            }
            set {
                this.lokpraw_dataRozpoczeciaDzialalnosciField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string lokpraw_dataWpisuDoRegon {
            get {
                return this.lokpraw_dataWpisuDoRegonField;
            }
            set {
                this.lokpraw_dataWpisuDoRegonField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string lokpraw_dataZawieszeniaDzialalnosci {
            get {
                return this.lokpraw_dataZawieszeniaDzialalnosciField;
            }
            set {
                this.lokpraw_dataZawieszeniaDzialalnosciField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string lokpraw_dataWznowieniaDzialalnosci {
            get {
                return this.lokpraw_dataWznowieniaDzialalnosciField;
            }
            set {
                this.lokpraw_dataWznowieniaDzialalnosciField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string lokpraw_dataZaistnieniaZmiany {
            get {
                return this.lokpraw_dataZaistnieniaZmianyField;
            }
            set {
                this.lokpraw_dataZaistnieniaZmianyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string lokpraw_dataZakonczeniaDzialalnosci {
            get {
                return this.lokpraw_dataZakonczeniaDzialalnosciField;
            }
            set {
                this.lokpraw_dataZakonczeniaDzialalnosciField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string lokpraw_dataSkresleniaZRegon {
            get {
                return this.lokpraw_dataSkresleniaZRegonField;
            }
            set {
                this.lokpraw_dataSkresleniaZRegonField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string lokpraw_adSiedzKraj_Symbol {
            get {
                return this.lokpraw_adSiedzKraj_SymbolField;
            }
            set {
                this.lokpraw_adSiedzKraj_SymbolField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string lokpraw_adSiedzWojewodztwo_Symbol {
            get {
                return this.lokpraw_adSiedzWojewodztwo_SymbolField;
            }
            set {
                this.lokpraw_adSiedzWojewodztwo_SymbolField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string lokpraw_adSiedzPowiat_Symbol {
            get {
                return this.lokpraw_adSiedzPowiat_SymbolField;
            }
            set {
                this.lokpraw_adSiedzPowiat_SymbolField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string lokpraw_adSiedzGmina_Symbol {
            get {
                return this.lokpraw_adSiedzGmina_SymbolField;
            }
            set {
                this.lokpraw_adSiedzGmina_SymbolField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string lokpraw_adSiedzKodPocztowy {
            get {
                return this.lokpraw_adSiedzKodPocztowyField;
            }
            set {
                this.lokpraw_adSiedzKodPocztowyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string lokpraw_adSiedzMiejscowoscPoczty_Symbol {
            get {
                return this.lokpraw_adSiedzMiejscowoscPoczty_SymbolField;
            }
            set {
                this.lokpraw_adSiedzMiejscowoscPoczty_SymbolField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string lokpraw_adSiedzMiejscowosc_Symbol {
            get {
                return this.lokpraw_adSiedzMiejscowosc_SymbolField;
            }
            set {
                this.lokpraw_adSiedzMiejscowosc_SymbolField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string lokpraw_adSiedzUlica_Symbol {
            get {
                return this.lokpraw_adSiedzUlica_SymbolField;
            }
            set {
                this.lokpraw_adSiedzUlica_SymbolField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string lokpraw_adSiedzNumerNieruchomosci {
            get {
                return this.lokpraw_adSiedzNumerNieruchomosciField;
            }
            set {
                this.lokpraw_adSiedzNumerNieruchomosciField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string lokpraw_adSiedzNumerLokalu {
            get {
                return this.lokpraw_adSiedzNumerLokaluField;
            }
            set {
                this.lokpraw_adSiedzNumerLokaluField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string lokpraw_adSiedzNietypoweMiejsceLokalizacji {
            get {
                return this.lokpraw_adSiedzNietypoweMiejsceLokalizacjiField;
            }
            set {
                this.lokpraw_adSiedzNietypoweMiejsceLokalizacjiField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string lokpraw_adSiedzKraj_Nazwa {
            get {
                return this.lokpraw_adSiedzKraj_NazwaField;
            }
            set {
                this.lokpraw_adSiedzKraj_NazwaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string lokpraw_adSiedzWojewodztwo_Nazwa {
            get {
                return this.lokpraw_adSiedzWojewodztwo_NazwaField;
            }
            set {
                this.lokpraw_adSiedzWojewodztwo_NazwaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string lokpraw_adSiedzPowiat_Nazwa {
            get {
                return this.lokpraw_adSiedzPowiat_NazwaField;
            }
            set {
                this.lokpraw_adSiedzPowiat_NazwaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string lokpraw_adSiedzGmina_Nazwa {
            get {
                return this.lokpraw_adSiedzGmina_NazwaField;
            }
            set {
                this.lokpraw_adSiedzGmina_NazwaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string lokpraw_adSiedzMiejscowosc_Nazwa {
            get {
                return this.lokpraw_adSiedzMiejscowosc_NazwaField;
            }
            set {
                this.lokpraw_adSiedzMiejscowosc_NazwaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string lokpraw_adSiedzMiejscowoscPoczty_Nazwa {
            get {
                return this.lokpraw_adSiedzMiejscowoscPoczty_NazwaField;
            }
            set {
                this.lokpraw_adSiedzMiejscowoscPoczty_NazwaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string lokpraw_adSiedzUlica_Nazwa {
            get {
                return this.lokpraw_adSiedzUlica_NazwaField;
            }
            set {
                this.lokpraw_adSiedzUlica_NazwaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string lokpraw_formaFinansowania_Symbol {
            get {
                return this.lokpraw_formaFinansowania_SymbolField;
            }
            set {
                this.lokpraw_formaFinansowania_SymbolField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string lokpraw_organRejestrowy_Symbol {
            get {
                return this.lokpraw_organRejestrowy_SymbolField;
            }
            set {
                this.lokpraw_organRejestrowy_SymbolField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string lokpraw_rodzajRejestruEwidencji_Symbol {
            get {
                return this.lokpraw_rodzajRejestruEwidencji_SymbolField;
            }
            set {
                this.lokpraw_rodzajRejestruEwidencji_SymbolField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string lokpraw_formaFinansowania_Nazwa {
            get {
                return this.lokpraw_formaFinansowania_NazwaField;
            }
            set {
                this.lokpraw_formaFinansowania_NazwaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string lokpraw_organRejestrowy_Nazwa {
            get {
                return this.lokpraw_organRejestrowy_NazwaField;
            }
            set {
                this.lokpraw_organRejestrowy_NazwaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string lokpraw_rodzajRejestruEwidencji_Nazwa {
            get {
                return this.lokpraw_rodzajRejestruEwidencji_NazwaField;
            }
            set {
                this.lokpraw_rodzajRejestruEwidencji_NazwaField = value;
            }
        }
    }
}
