//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.8.3928.0.
// 
namespace Gus.Regon.BIR11.Proxy.Models.DanePobierzPelnyRaport.BIR11OsFizycznaListaJednLokalnych
{
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class root {
        
        private rootDane[] daneField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("dane", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public rootDane[] dane {
            get {
                return this.daneField;
            }
            set {
                this.daneField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class rootDane {
        
        private string lokfiz_regon14Field;
        
        private string lokfiz_nazwaField;
        
        private int lokfiz_silosIDField;
        
        private bool lokfiz_silosIDFieldSpecified;
        
        private string lokfiz_silos_SymbolField;
        
        private string lokfiz_adSiedzKraj_SymbolField;
        
        private string lokfiz_adSiedzWojewodztwo_SymbolField;
        
        private string lokfiz_adSiedzPowiat_SymbolField;
        
        private string lokfiz_adSiedzGmina_SymbolField;
        
        private string lokfiz_adSiedzKodPocztowyField;
        
        private string lokfiz_adSiedzMiejscowoscPoczty_SymbolField;
        
        private string lokfiz_adSiedzMiejscowosc_SymbolField;
        
        private string lokfiz_adSiedzUlica_SymbolField;
        
        private string lokfiz_adSiedzNumerNieruchomosciField;
        
        private string lokfiz_adSiedzNumerLokaluField;
        
        private string lokfiz_adSiedzNietypoweMiejsceLokalizacjiField;
        
        private string lokfiz_adSiedzWojewodztwo_NazwaField;
        
        private string lokfiz_adSiedzPowiat_NazwaField;
        
        private string lokfiz_adSiedzGmina_NazwaField;
        
        private string lokfiz_adSiedzMiejscowosc_NazwaField;
        
        private string lokfiz_adSiedzMiejscowoscPoczty_NazwaField;
        
        private string lokfiz_adSiedzUlica_NazwaField;
        
        private string lokfiz_dataPowstaniaField;
        
        private string lokfiz_dataRozpoczeciaDzialalnosciField;
        
        private string lokfiz_dataWpisuDoRegonField;
        
        private string lokfiz_dataZawieszeniaDzialalnosciField;
        
        private string lokfiz_dataWznowieniaDzialalnosciField;
        
        private string lokfiz_dataZakonczeniaDzialalnosciField;
        
        private string lokfiz_dataSkresleniaZRegonField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string lokfiz_regon14 {
            get {
                return this.lokfiz_regon14Field;
            }
            set {
                this.lokfiz_regon14Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string lokfiz_nazwa {
            get {
                return this.lokfiz_nazwaField;
            }
            set {
                this.lokfiz_nazwaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int lokfiz_silosID {
            get {
                return this.lokfiz_silosIDField;
            }
            set {
                this.lokfiz_silosIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool lokfiz_silosIDSpecified {
            get {
                return this.lokfiz_silosIDFieldSpecified;
            }
            set {
                this.lokfiz_silosIDFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string lokfiz_silos_Symbol {
            get {
                return this.lokfiz_silos_SymbolField;
            }
            set {
                this.lokfiz_silos_SymbolField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string lokfiz_adSiedzKraj_Symbol {
            get {
                return this.lokfiz_adSiedzKraj_SymbolField;
            }
            set {
                this.lokfiz_adSiedzKraj_SymbolField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string lokfiz_adSiedzWojewodztwo_Symbol {
            get {
                return this.lokfiz_adSiedzWojewodztwo_SymbolField;
            }
            set {
                this.lokfiz_adSiedzWojewodztwo_SymbolField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string lokfiz_adSiedzPowiat_Symbol {
            get {
                return this.lokfiz_adSiedzPowiat_SymbolField;
            }
            set {
                this.lokfiz_adSiedzPowiat_SymbolField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string lokfiz_adSiedzGmina_Symbol {
            get {
                return this.lokfiz_adSiedzGmina_SymbolField;
            }
            set {
                this.lokfiz_adSiedzGmina_SymbolField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string lokfiz_adSiedzKodPocztowy {
            get {
                return this.lokfiz_adSiedzKodPocztowyField;
            }
            set {
                this.lokfiz_adSiedzKodPocztowyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string lokfiz_adSiedzMiejscowoscPoczty_Symbol {
            get {
                return this.lokfiz_adSiedzMiejscowoscPoczty_SymbolField;
            }
            set {
                this.lokfiz_adSiedzMiejscowoscPoczty_SymbolField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string lokfiz_adSiedzMiejscowosc_Symbol {
            get {
                return this.lokfiz_adSiedzMiejscowosc_SymbolField;
            }
            set {
                this.lokfiz_adSiedzMiejscowosc_SymbolField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string lokfiz_adSiedzUlica_Symbol {
            get {
                return this.lokfiz_adSiedzUlica_SymbolField;
            }
            set {
                this.lokfiz_adSiedzUlica_SymbolField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string lokfiz_adSiedzNumerNieruchomosci {
            get {
                return this.lokfiz_adSiedzNumerNieruchomosciField;
            }
            set {
                this.lokfiz_adSiedzNumerNieruchomosciField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string lokfiz_adSiedzNumerLokalu {
            get {
                return this.lokfiz_adSiedzNumerLokaluField;
            }
            set {
                this.lokfiz_adSiedzNumerLokaluField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string lokfiz_adSiedzNietypoweMiejsceLokalizacji {
            get {
                return this.lokfiz_adSiedzNietypoweMiejsceLokalizacjiField;
            }
            set {
                this.lokfiz_adSiedzNietypoweMiejsceLokalizacjiField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string lokfiz_adSiedzWojewodztwo_Nazwa {
            get {
                return this.lokfiz_adSiedzWojewodztwo_NazwaField;
            }
            set {
                this.lokfiz_adSiedzWojewodztwo_NazwaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string lokfiz_adSiedzPowiat_Nazwa {
            get {
                return this.lokfiz_adSiedzPowiat_NazwaField;
            }
            set {
                this.lokfiz_adSiedzPowiat_NazwaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string lokfiz_adSiedzGmina_Nazwa {
            get {
                return this.lokfiz_adSiedzGmina_NazwaField;
            }
            set {
                this.lokfiz_adSiedzGmina_NazwaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string lokfiz_adSiedzMiejscowosc_Nazwa {
            get {
                return this.lokfiz_adSiedzMiejscowosc_NazwaField;
            }
            set {
                this.lokfiz_adSiedzMiejscowosc_NazwaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string lokfiz_adSiedzMiejscowoscPoczty_Nazwa {
            get {
                return this.lokfiz_adSiedzMiejscowoscPoczty_NazwaField;
            }
            set {
                this.lokfiz_adSiedzMiejscowoscPoczty_NazwaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string lokfiz_adSiedzUlica_Nazwa {
            get {
                return this.lokfiz_adSiedzUlica_NazwaField;
            }
            set {
                this.lokfiz_adSiedzUlica_NazwaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string lokfiz_dataPowstania {
            get {
                return this.lokfiz_dataPowstaniaField;
            }
            set {
                this.lokfiz_dataPowstaniaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string lokfiz_dataRozpoczeciaDzialalnosci {
            get {
                return this.lokfiz_dataRozpoczeciaDzialalnosciField;
            }
            set {
                this.lokfiz_dataRozpoczeciaDzialalnosciField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string lokfiz_dataWpisuDoRegon {
            get {
                return this.lokfiz_dataWpisuDoRegonField;
            }
            set {
                this.lokfiz_dataWpisuDoRegonField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string lokfiz_dataZawieszeniaDzialalnosci {
            get {
                return this.lokfiz_dataZawieszeniaDzialalnosciField;
            }
            set {
                this.lokfiz_dataZawieszeniaDzialalnosciField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string lokfiz_dataWznowieniaDzialalnosci {
            get {
                return this.lokfiz_dataWznowieniaDzialalnosciField;
            }
            set {
                this.lokfiz_dataWznowieniaDzialalnosciField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string lokfiz_dataZakonczeniaDzialalnosci {
            get {
                return this.lokfiz_dataZakonczeniaDzialalnosciField;
            }
            set {
                this.lokfiz_dataZakonczeniaDzialalnosciField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string lokfiz_dataSkresleniaZRegon {
            get {
                return this.lokfiz_dataSkresleniaZRegonField;
            }
            set {
                this.lokfiz_dataSkresleniaZRegonField = value;
            }
        }
    }
}
