//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.8.3928.0.
// 
namespace Gus.Regon.BIR11.Proxy.Models.DanePobierzPelnyRaport.BIR11OsPrawna
{
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class root {
        
        private rootDane daneField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public rootDane dane {
            get {
                return this.daneField;
            }
            set {
                this.daneField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class rootDane {
        
        private string praw_regon9Field;
        
        private string praw_nipField;
        
        private rootDanePraw_statusNip praw_statusNipField;
        
        private bool praw_statusNipFieldSpecified;
        
        private string praw_nazwaField;
        
        private string praw_nazwaSkroconaField;
        
        private string praw_numerWRejestrzeEwidencjiField;
        
        private string praw_dataWpisuDoRejestruEwidencjiField;
        
        private string praw_dataPowstaniaField;
        
        private string praw_dataRozpoczeciaDzialalnosciField;
        
        private string praw_dataWpisuDoRegonField;
        
        private string praw_dataZawieszeniaDzialalnosciField;
        
        private string praw_dataWznowieniaDzialalnosciField;
        
        private string praw_dataZaistnieniaZmianyField;
        
        private string praw_dataZakonczeniaDzialalnosciField;
        
        private string praw_dataSkresleniaZRegonField;
        
        private string praw_dataOrzeczeniaOUpadlosciField;
        
        private string praw_dataZakonczeniaPostepowaniaUpadlosciowegoField;
        
        private string praw_adSiedzKraj_SymbolField;
        
        private string praw_adSiedzWojewodztwo_SymbolField;
        
        private string praw_adSiedzPowiat_SymbolField;
        
        private string praw_adSiedzGmina_SymbolField;
        
        private string praw_adSiedzKodPocztowyField;
        
        private string praw_adSiedzMiejscowoscPoczty_SymbolField;
        
        private string praw_adSiedzMiejscowosc_SymbolField;
        
        private string praw_adSiedzUlica_SymbolField;
        
        private string praw_adSiedzNumerNieruchomosciField;
        
        private string praw_adSiedzNumerLokaluField;
        
        private string praw_adSiedzNietypoweMiejsceLokalizacjiField;
        
        private string praw_numerTelefonuField;
        
        private string praw_numerWewnetrznyTelefonuField;
        
        private string praw_numerFaksuField;
        
        private string praw_adresEmailField;
        
        private string praw_adresStronyinternetowejField;
        
        private string praw_adSiedzKraj_NazwaField;
        
        private string praw_adSiedzWojewodztwo_NazwaField;
        
        private string praw_adSiedzPowiat_NazwaField;
        
        private string praw_adSiedzGmina_NazwaField;
        
        private string praw_adSiedzMiejscowosc_NazwaField;
        
        private string praw_adSiedzMiejscowoscPoczty_NazwaField;
        
        private string praw_adSiedzUlica_NazwaField;
        
        private string praw_podstawowaFormaPrawna_SymbolField;
        
        private string praw_szczegolnaFormaPrawna_SymbolField;
        
        private string praw_formaFinansowania_SymbolField;
        
        private string praw_formaWlasnosci_SymbolField;
        
        private string praw_organZalozycielski_SymbolField;
        
        private string praw_organRejestrowy_SymbolField;
        
        private string praw_rodzajRejestruEwidencji_SymbolField;
        
        private string praw_podstawowaFormaPrawna_NazwaField;
        
        private string praw_szczegolnaFormaPrawna_NazwaField;
        
        private string praw_formaFinansowania_NazwaField;
        
        private string praw_formaWlasnosci_NazwaField;
        
        private string praw_organZalozycielski_NazwaField;
        
        private string praw_organRejestrowy_NazwaField;
        
        private string praw_rodzajRejestruEwidencji_NazwaField;
        
        private int praw_liczbaJednLokalnychField;
        
        private bool praw_liczbaJednLokalnychFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string praw_regon9 {
            get {
                return this.praw_regon9Field;
            }
            set {
                this.praw_regon9Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string praw_nip {
            get {
                return this.praw_nipField;
            }
            set {
                this.praw_nipField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public rootDanePraw_statusNip praw_statusNip {
            get {
                return this.praw_statusNipField;
            }
            set {
                this.praw_statusNipField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool praw_statusNipSpecified {
            get {
                return this.praw_statusNipFieldSpecified;
            }
            set {
                this.praw_statusNipFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string praw_nazwa {
            get {
                return this.praw_nazwaField;
            }
            set {
                this.praw_nazwaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string praw_nazwaSkrocona {
            get {
                return this.praw_nazwaSkroconaField;
            }
            set {
                this.praw_nazwaSkroconaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string praw_numerWRejestrzeEwidencji {
            get {
                return this.praw_numerWRejestrzeEwidencjiField;
            }
            set {
                this.praw_numerWRejestrzeEwidencjiField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string praw_dataWpisuDoRejestruEwidencji {
            get {
                return this.praw_dataWpisuDoRejestruEwidencjiField;
            }
            set {
                this.praw_dataWpisuDoRejestruEwidencjiField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string praw_dataPowstania {
            get {
                return this.praw_dataPowstaniaField;
            }
            set {
                this.praw_dataPowstaniaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string praw_dataRozpoczeciaDzialalnosci {
            get {
                return this.praw_dataRozpoczeciaDzialalnosciField;
            }
            set {
                this.praw_dataRozpoczeciaDzialalnosciField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string praw_dataWpisuDoRegon {
            get {
                return this.praw_dataWpisuDoRegonField;
            }
            set {
                this.praw_dataWpisuDoRegonField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string praw_dataZawieszeniaDzialalnosci {
            get {
                return this.praw_dataZawieszeniaDzialalnosciField;
            }
            set {
                this.praw_dataZawieszeniaDzialalnosciField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string praw_dataWznowieniaDzialalnosci {
            get {
                return this.praw_dataWznowieniaDzialalnosciField;
            }
            set {
                this.praw_dataWznowieniaDzialalnosciField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string praw_dataZaistnieniaZmiany {
            get {
                return this.praw_dataZaistnieniaZmianyField;
            }
            set {
                this.praw_dataZaistnieniaZmianyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string praw_dataZakonczeniaDzialalnosci {
            get {
                return this.praw_dataZakonczeniaDzialalnosciField;
            }
            set {
                this.praw_dataZakonczeniaDzialalnosciField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string praw_dataSkresleniaZRegon {
            get {
                return this.praw_dataSkresleniaZRegonField;
            }
            set {
                this.praw_dataSkresleniaZRegonField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string praw_dataOrzeczeniaOUpadlosci {
            get {
                return this.praw_dataOrzeczeniaOUpadlosciField;
            }
            set {
                this.praw_dataOrzeczeniaOUpadlosciField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string praw_dataZakonczeniaPostepowaniaUpadlosciowego {
            get {
                return this.praw_dataZakonczeniaPostepowaniaUpadlosciowegoField;
            }
            set {
                this.praw_dataZakonczeniaPostepowaniaUpadlosciowegoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string praw_adSiedzKraj_Symbol {
            get {
                return this.praw_adSiedzKraj_SymbolField;
            }
            set {
                this.praw_adSiedzKraj_SymbolField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string praw_adSiedzWojewodztwo_Symbol {
            get {
                return this.praw_adSiedzWojewodztwo_SymbolField;
            }
            set {
                this.praw_adSiedzWojewodztwo_SymbolField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string praw_adSiedzPowiat_Symbol {
            get {
                return this.praw_adSiedzPowiat_SymbolField;
            }
            set {
                this.praw_adSiedzPowiat_SymbolField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string praw_adSiedzGmina_Symbol {
            get {
                return this.praw_adSiedzGmina_SymbolField;
            }
            set {
                this.praw_adSiedzGmina_SymbolField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string praw_adSiedzKodPocztowy {
            get {
                return this.praw_adSiedzKodPocztowyField;
            }
            set {
                this.praw_adSiedzKodPocztowyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string praw_adSiedzMiejscowoscPoczty_Symbol {
            get {
                return this.praw_adSiedzMiejscowoscPoczty_SymbolField;
            }
            set {
                this.praw_adSiedzMiejscowoscPoczty_SymbolField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string praw_adSiedzMiejscowosc_Symbol {
            get {
                return this.praw_adSiedzMiejscowosc_SymbolField;
            }
            set {
                this.praw_adSiedzMiejscowosc_SymbolField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string praw_adSiedzUlica_Symbol {
            get {
                return this.praw_adSiedzUlica_SymbolField;
            }
            set {
                this.praw_adSiedzUlica_SymbolField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string praw_adSiedzNumerNieruchomosci {
            get {
                return this.praw_adSiedzNumerNieruchomosciField;
            }
            set {
                this.praw_adSiedzNumerNieruchomosciField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string praw_adSiedzNumerLokalu {
            get {
                return this.praw_adSiedzNumerLokaluField;
            }
            set {
                this.praw_adSiedzNumerLokaluField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string praw_adSiedzNietypoweMiejsceLokalizacji {
            get {
                return this.praw_adSiedzNietypoweMiejsceLokalizacjiField;
            }
            set {
                this.praw_adSiedzNietypoweMiejsceLokalizacjiField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string praw_numerTelefonu {
            get {
                return this.praw_numerTelefonuField;
            }
            set {
                this.praw_numerTelefonuField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string praw_numerWewnetrznyTelefonu {
            get {
                return this.praw_numerWewnetrznyTelefonuField;
            }
            set {
                this.praw_numerWewnetrznyTelefonuField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string praw_numerFaksu {
            get {
                return this.praw_numerFaksuField;
            }
            set {
                this.praw_numerFaksuField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string praw_adresEmail {
            get {
                return this.praw_adresEmailField;
            }
            set {
                this.praw_adresEmailField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string praw_adresStronyinternetowej {
            get {
                return this.praw_adresStronyinternetowejField;
            }
            set {
                this.praw_adresStronyinternetowejField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string praw_adSiedzKraj_Nazwa {
            get {
                return this.praw_adSiedzKraj_NazwaField;
            }
            set {
                this.praw_adSiedzKraj_NazwaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string praw_adSiedzWojewodztwo_Nazwa {
            get {
                return this.praw_adSiedzWojewodztwo_NazwaField;
            }
            set {
                this.praw_adSiedzWojewodztwo_NazwaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string praw_adSiedzPowiat_Nazwa {
            get {
                return this.praw_adSiedzPowiat_NazwaField;
            }
            set {
                this.praw_adSiedzPowiat_NazwaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string praw_adSiedzGmina_Nazwa {
            get {
                return this.praw_adSiedzGmina_NazwaField;
            }
            set {
                this.praw_adSiedzGmina_NazwaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string praw_adSiedzMiejscowosc_Nazwa {
            get {
                return this.praw_adSiedzMiejscowosc_NazwaField;
            }
            set {
                this.praw_adSiedzMiejscowosc_NazwaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string praw_adSiedzMiejscowoscPoczty_Nazwa {
            get {
                return this.praw_adSiedzMiejscowoscPoczty_NazwaField;
            }
            set {
                this.praw_adSiedzMiejscowoscPoczty_NazwaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string praw_adSiedzUlica_Nazwa {
            get {
                return this.praw_adSiedzUlica_NazwaField;
            }
            set {
                this.praw_adSiedzUlica_NazwaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string praw_podstawowaFormaPrawna_Symbol {
            get {
                return this.praw_podstawowaFormaPrawna_SymbolField;
            }
            set {
                this.praw_podstawowaFormaPrawna_SymbolField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string praw_szczegolnaFormaPrawna_Symbol {
            get {
                return this.praw_szczegolnaFormaPrawna_SymbolField;
            }
            set {
                this.praw_szczegolnaFormaPrawna_SymbolField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string praw_formaFinansowania_Symbol {
            get {
                return this.praw_formaFinansowania_SymbolField;
            }
            set {
                this.praw_formaFinansowania_SymbolField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string praw_formaWlasnosci_Symbol {
            get {
                return this.praw_formaWlasnosci_SymbolField;
            }
            set {
                this.praw_formaWlasnosci_SymbolField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string praw_organZalozycielski_Symbol {
            get {
                return this.praw_organZalozycielski_SymbolField;
            }
            set {
                this.praw_organZalozycielski_SymbolField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string praw_organRejestrowy_Symbol {
            get {
                return this.praw_organRejestrowy_SymbolField;
            }
            set {
                this.praw_organRejestrowy_SymbolField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string praw_rodzajRejestruEwidencji_Symbol {
            get {
                return this.praw_rodzajRejestruEwidencji_SymbolField;
            }
            set {
                this.praw_rodzajRejestruEwidencji_SymbolField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string praw_podstawowaFormaPrawna_Nazwa {
            get {
                return this.praw_podstawowaFormaPrawna_NazwaField;
            }
            set {
                this.praw_podstawowaFormaPrawna_NazwaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string praw_szczegolnaFormaPrawna_Nazwa {
            get {
                return this.praw_szczegolnaFormaPrawna_NazwaField;
            }
            set {
                this.praw_szczegolnaFormaPrawna_NazwaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string praw_formaFinansowania_Nazwa {
            get {
                return this.praw_formaFinansowania_NazwaField;
            }
            set {
                this.praw_formaFinansowania_NazwaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string praw_formaWlasnosci_Nazwa {
            get {
                return this.praw_formaWlasnosci_NazwaField;
            }
            set {
                this.praw_formaWlasnosci_NazwaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string praw_organZalozycielski_Nazwa {
            get {
                return this.praw_organZalozycielski_NazwaField;
            }
            set {
                this.praw_organZalozycielski_NazwaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string praw_organRejestrowy_Nazwa {
            get {
                return this.praw_organRejestrowy_NazwaField;
            }
            set {
                this.praw_organRejestrowy_NazwaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string praw_rodzajRejestruEwidencji_Nazwa {
            get {
                return this.praw_rodzajRejestruEwidencji_NazwaField;
            }
            set {
                this.praw_rodzajRejestruEwidencji_NazwaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int praw_liczbaJednLokalnych {
            get {
                return this.praw_liczbaJednLokalnychField;
            }
            set {
                this.praw_liczbaJednLokalnychField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool praw_liczbaJednLokalnychSpecified {
            get {
                return this.praw_liczbaJednLokalnychFieldSpecified;
            }
            set {
                this.praw_liczbaJednLokalnychFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public enum rootDanePraw_statusNip {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("")]
        Item,
        
        /// <remarks/>
        Uchylony,
        
        /// <remarks/>
        Unieważniony,
    }
}
