//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.8.3928.0.
// 
namespace Gus.Regon.BIR11.Proxy.Models.DanePobierzPelnyRaport.BIR11OsFizycznaDzialalnoscSkreslonaDo20141108
{
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class root {
        
        private rootDane daneField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public rootDane dane {
            get {
                return this.daneField;
            }
            set {
                this.daneField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class rootDane {
        
        private string fiz_regon9Field;
        
        private string fiz_nazwaField;
        
        private string fiz_nazwaSkroconaField;
        
        private string fiz_dataPowstaniaField;
        
        private string fiz_dataRozpoczeciaDzialalnosciField;
        
        private string fiz_dataWpisuDzialalnosciDoRegonField;
        
        private string fiz_dataZawieszeniaDzialalnosciField;
        
        private string fiz_dataWznowieniaDzialalnosciField;
        
        private string fiz_dataZaistnieniaZmianyDzialalnosciField;
        
        private string fiz_dataZakonczeniaDzialalnosciField;
        
        private string fiz_dataSkresleniaDzialalnosciZRegonField;
        
        private string fiz_adSiedzKraj_SymbolField;
        
        private string fiz_adSiedzWojewodztwo_SymbolField;
        
        private string fiz_adSiedzPowiat_SymbolField;
        
        private string fiz_adSiedzGmina_SymbolField;
        
        private string fiz_adSiedzKodPocztowyField;
        
        private string fiz_adSiedzMiejscowoscPoczty_SymbolField;
        
        private string fiz_adSiedzMiejscowosc_SymbolField;
        
        private string fiz_adSiedzUlica_SymbolField;
        
        private string fiz_adSiedzNumerNieruchomosciField;
        
        private string fiz_adSiedzNumerLokaluField;
        
        private string fiz_adSiedzNietypoweMiejsceLokalizacjiField;
        
        private string fiz_numerTelefonuField;
        
        private string fiz_numerWewnetrznyTelefonuField;
        
        private string fiz_numerFaksuField;
        
        private string fiz_adresEmailField;
        
        private string fiz_adresStronyinternetowejField;
        
        private string fiz_adresEmail2Field;
        
        private string fiz_adSiedzKraj_NazwaField;
        
        private string fiz_adSiedzWojewodztwo_NazwaField;
        
        private string fiz_adSiedzPowiat_NazwaField;
        
        private string fiz_adSiedzGmina_NazwaField;
        
        private string fiz_adSiedzMiejscowosc_NazwaField;
        
        private string fiz_adSiedzMiejscowoscPoczty_NazwaField;
        
        private string fiz_adSiedzUlica_NazwaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string fiz_regon9 {
            get {
                return this.fiz_regon9Field;
            }
            set {
                this.fiz_regon9Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string fiz_nazwa {
            get {
                return this.fiz_nazwaField;
            }
            set {
                this.fiz_nazwaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string fiz_nazwaSkrocona {
            get {
                return this.fiz_nazwaSkroconaField;
            }
            set {
                this.fiz_nazwaSkroconaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string fiz_dataPowstania {
            get {
                return this.fiz_dataPowstaniaField;
            }
            set {
                this.fiz_dataPowstaniaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string fiz_dataRozpoczeciaDzialalnosci {
            get {
                return this.fiz_dataRozpoczeciaDzialalnosciField;
            }
            set {
                this.fiz_dataRozpoczeciaDzialalnosciField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string fiz_dataWpisuDzialalnosciDoRegon {
            get {
                return this.fiz_dataWpisuDzialalnosciDoRegonField;
            }
            set {
                this.fiz_dataWpisuDzialalnosciDoRegonField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string fiz_dataZawieszeniaDzialalnosci {
            get {
                return this.fiz_dataZawieszeniaDzialalnosciField;
            }
            set {
                this.fiz_dataZawieszeniaDzialalnosciField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string fiz_dataWznowieniaDzialalnosci {
            get {
                return this.fiz_dataWznowieniaDzialalnosciField;
            }
            set {
                this.fiz_dataWznowieniaDzialalnosciField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string fiz_dataZaistnieniaZmianyDzialalnosci {
            get {
                return this.fiz_dataZaistnieniaZmianyDzialalnosciField;
            }
            set {
                this.fiz_dataZaistnieniaZmianyDzialalnosciField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string fiz_dataZakonczeniaDzialalnosci {
            get {
                return this.fiz_dataZakonczeniaDzialalnosciField;
            }
            set {
                this.fiz_dataZakonczeniaDzialalnosciField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string fiz_dataSkresleniaDzialalnosciZRegon {
            get {
                return this.fiz_dataSkresleniaDzialalnosciZRegonField;
            }
            set {
                this.fiz_dataSkresleniaDzialalnosciZRegonField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string fiz_adSiedzKraj_Symbol {
            get {
                return this.fiz_adSiedzKraj_SymbolField;
            }
            set {
                this.fiz_adSiedzKraj_SymbolField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string fiz_adSiedzWojewodztwo_Symbol {
            get {
                return this.fiz_adSiedzWojewodztwo_SymbolField;
            }
            set {
                this.fiz_adSiedzWojewodztwo_SymbolField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string fiz_adSiedzPowiat_Symbol {
            get {
                return this.fiz_adSiedzPowiat_SymbolField;
            }
            set {
                this.fiz_adSiedzPowiat_SymbolField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string fiz_adSiedzGmina_Symbol {
            get {
                return this.fiz_adSiedzGmina_SymbolField;
            }
            set {
                this.fiz_adSiedzGmina_SymbolField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string fiz_adSiedzKodPocztowy {
            get {
                return this.fiz_adSiedzKodPocztowyField;
            }
            set {
                this.fiz_adSiedzKodPocztowyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string fiz_adSiedzMiejscowoscPoczty_Symbol {
            get {
                return this.fiz_adSiedzMiejscowoscPoczty_SymbolField;
            }
            set {
                this.fiz_adSiedzMiejscowoscPoczty_SymbolField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string fiz_adSiedzMiejscowosc_Symbol {
            get {
                return this.fiz_adSiedzMiejscowosc_SymbolField;
            }
            set {
                this.fiz_adSiedzMiejscowosc_SymbolField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string fiz_adSiedzUlica_Symbol {
            get {
                return this.fiz_adSiedzUlica_SymbolField;
            }
            set {
                this.fiz_adSiedzUlica_SymbolField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string fiz_adSiedzNumerNieruchomosci {
            get {
                return this.fiz_adSiedzNumerNieruchomosciField;
            }
            set {
                this.fiz_adSiedzNumerNieruchomosciField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string fiz_adSiedzNumerLokalu {
            get {
                return this.fiz_adSiedzNumerLokaluField;
            }
            set {
                this.fiz_adSiedzNumerLokaluField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string fiz_adSiedzNietypoweMiejsceLokalizacji {
            get {
                return this.fiz_adSiedzNietypoweMiejsceLokalizacjiField;
            }
            set {
                this.fiz_adSiedzNietypoweMiejsceLokalizacjiField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string fiz_numerTelefonu {
            get {
                return this.fiz_numerTelefonuField;
            }
            set {
                this.fiz_numerTelefonuField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string fiz_numerWewnetrznyTelefonu {
            get {
                return this.fiz_numerWewnetrznyTelefonuField;
            }
            set {
                this.fiz_numerWewnetrznyTelefonuField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string fiz_numerFaksu {
            get {
                return this.fiz_numerFaksuField;
            }
            set {
                this.fiz_numerFaksuField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string fiz_adresEmail {
            get {
                return this.fiz_adresEmailField;
            }
            set {
                this.fiz_adresEmailField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string fiz_adresStronyinternetowej {
            get {
                return this.fiz_adresStronyinternetowejField;
            }
            set {
                this.fiz_adresStronyinternetowejField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string fiz_adresEmail2 {
            get {
                return this.fiz_adresEmail2Field;
            }
            set {
                this.fiz_adresEmail2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string fiz_adSiedzKraj_Nazwa {
            get {
                return this.fiz_adSiedzKraj_NazwaField;
            }
            set {
                this.fiz_adSiedzKraj_NazwaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string fiz_adSiedzWojewodztwo_Nazwa {
            get {
                return this.fiz_adSiedzWojewodztwo_NazwaField;
            }
            set {
                this.fiz_adSiedzWojewodztwo_NazwaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string fiz_adSiedzPowiat_Nazwa {
            get {
                return this.fiz_adSiedzPowiat_NazwaField;
            }
            set {
                this.fiz_adSiedzPowiat_NazwaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string fiz_adSiedzGmina_Nazwa {
            get {
                return this.fiz_adSiedzGmina_NazwaField;
            }
            set {
                this.fiz_adSiedzGmina_NazwaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string fiz_adSiedzMiejscowosc_Nazwa {
            get {
                return this.fiz_adSiedzMiejscowosc_NazwaField;
            }
            set {
                this.fiz_adSiedzMiejscowosc_NazwaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string fiz_adSiedzMiejscowoscPoczty_Nazwa {
            get {
                return this.fiz_adSiedzMiejscowoscPoczty_NazwaField;
            }
            set {
                this.fiz_adSiedzMiejscowoscPoczty_NazwaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string fiz_adSiedzUlica_Nazwa {
            get {
                return this.fiz_adSiedzUlica_NazwaField;
            }
            set {
                this.fiz_adSiedzUlica_NazwaField = value;
            }
        }
    }
}
