//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.8.3928.0.
// 
namespace Gus.Regon.BIR11.Proxy.Models.DanePobierzPelnyRaport.BIR11OsFizycznaPkd
{
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class root {
        
        private rootDane[] daneField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("dane", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public rootDane[] dane {
            get {
                return this.daneField;
            }
            set {
                this.daneField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class rootDane {
        
        private string fiz_pkd_KodField;
        
        private string fiz_pkd_NazwaField;
        
        private string fiz_pkd_PrzewazajaceField;
        
        private int fiz_SilosIDField;
        
        private bool fiz_SilosIDFieldSpecified;
        
        private string fiz_Silos_SymbolField;
        
        private string fiz_dataSkresleniaDzialalnosciZRegonField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string fiz_pkd_Kod {
            get {
                return this.fiz_pkd_KodField;
            }
            set {
                this.fiz_pkd_KodField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string fiz_pkd_Nazwa {
            get {
                return this.fiz_pkd_NazwaField;
            }
            set {
                this.fiz_pkd_NazwaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string fiz_pkd_Przewazajace {
            get {
                return this.fiz_pkd_PrzewazajaceField;
            }
            set {
                this.fiz_pkd_PrzewazajaceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int fiz_SilosID {
            get {
                return this.fiz_SilosIDField;
            }
            set {
                this.fiz_SilosIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fiz_SilosIDSpecified {
            get {
                return this.fiz_SilosIDFieldSpecified;
            }
            set {
                this.fiz_SilosIDFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string fiz_Silos_Symbol {
            get {
                return this.fiz_Silos_SymbolField;
            }
            set {
                this.fiz_Silos_SymbolField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string fiz_dataSkresleniaDzialalnosciZRegon {
            get {
                return this.fiz_dataSkresleniaDzialalnosciZRegonField;
            }
            set {
                this.fiz_dataSkresleniaDzialalnosciZRegonField = value;
            }
        }
    }
}
