//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.8.3928.0.
// 
namespace Gus.Regon.BIR11.Proxy.Models.DanePobierzPelnyRaport.BIR11JednLokalnaOsFizycznejPkd
{
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class root {
        
        private rootDane[] daneField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("dane", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public rootDane[] dane {
            get {
                return this.daneField;
            }
            set {
                this.daneField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class rootDane {
        
        private string lokfiz_pkd_KodField;
        
        private string lokfiz_pkd_NazwaField;
        
        private string lokfiz_pkd_PrzewazajaceField;
        
        private string lokfiz_Silos_SymbolField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string lokfiz_pkd_Kod {
            get {
                return this.lokfiz_pkd_KodField;
            }
            set {
                this.lokfiz_pkd_KodField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string lokfiz_pkd_Nazwa {
            get {
                return this.lokfiz_pkd_NazwaField;
            }
            set {
                this.lokfiz_pkd_NazwaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string lokfiz_pkd_Przewazajace {
            get {
                return this.lokfiz_pkd_PrzewazajaceField;
            }
            set {
                this.lokfiz_pkd_PrzewazajaceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string lokfiz_Silos_Symbol {
            get {
                return this.lokfiz_Silos_SymbolField;
            }
            set {
                this.lokfiz_Silos_SymbolField = value;
            }
        }
    }
}
