//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.8.3928.0.
// 
namespace Gus.Regon.BIR11.Proxy.Models.DanePobierzPelnyRaport.BIR11OsPrawnaSpCywilnaWspolnicy
{
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class root {
        
        private rootDane[] daneField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("dane", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public rootDane[] dane {
            get {
                return this.daneField;
            }
            set {
                this.daneField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class rootDane {
        
        private string wspolsc_regonWspolnikSpolkiField;
        
        private string wspolsc_imiePierwszeField;
        
        private string wspolsc_imieDrugieField;
        
        private string wspolsc_nazwiskoField;
        
        private string wspolsc_firmaNazwaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string wspolsc_regonWspolnikSpolki {
            get {
                return this.wspolsc_regonWspolnikSpolkiField;
            }
            set {
                this.wspolsc_regonWspolnikSpolkiField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string wspolsc_imiePierwsze {
            get {
                return this.wspolsc_imiePierwszeField;
            }
            set {
                this.wspolsc_imiePierwszeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string wspolsc_imieDrugie {
            get {
                return this.wspolsc_imieDrugieField;
            }
            set {
                this.wspolsc_imieDrugieField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string wspolsc_nazwisko {
            get {
                return this.wspolsc_nazwiskoField;
            }
            set {
                this.wspolsc_nazwiskoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string wspolsc_firmaNazwa {
            get {
                return this.wspolsc_firmaNazwaField;
            }
            set {
                this.wspolsc_firmaNazwaField = value;
            }
        }
    }
}
