//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.8.3928.0.
// 
namespace Gus.Regon.BIR11.Proxy.Models.DanePobierzPelnyRaport.BIR11OsFizycznaDaneOgolne
{
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class root {
        
        private rootDane daneField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public rootDane dane {
            get {
                return this.daneField;
            }
            set {
                this.daneField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class rootDane {
        
        private string fiz_regon9Field;
        
        private string fiz_nipField;
        
        private rootDaneFiz_statusNip fiz_statusNipField;
        
        private bool fiz_statusNipFieldSpecified;
        
        private string fiz_nazwiskoField;
        
        private string fiz_imie1Field;
        
        private string fiz_imie2Field;
        
        private string fiz_dataWpisuPodmiotuDoRegonField;
        
        private string fiz_dataZaistnieniaZmianyField;
        
        private string fiz_dataSkresleniaPodmiotuZRegonField;
        
        private string fiz_podstawowaFormaPrawna_SymbolField;
        
        private string fiz_szczegolnaFormaPrawna_SymbolField;
        
        private string fiz_formaFinansowania_SymbolField;
        
        private string fiz_formaWlasnosci_SymbolField;
        
        private string fiz_podstawowaFormaPrawna_NazwaField;
        
        private string fiz_szczegolnaFormaPrawna_NazwaField;
        
        private string fiz_formaFinansowania_NazwaField;
        
        private string fiz_formaWlasnosci_NazwaField;
        
        private int fiz_dzialalnoscCeidgField;
        
        private bool fiz_dzialalnoscCeidgFieldSpecified;
        
        private int fiz_dzialalnoscRolniczaField;
        
        private bool fiz_dzialalnoscRolniczaFieldSpecified;
        
        private int fiz_dzialalnoscPozostalaField;
        
        private bool fiz_dzialalnoscPozostalaFieldSpecified;
        
        private int fiz_dzialalnoscSkreslonaDo20141108Field;
        
        private bool fiz_dzialalnoscSkreslonaDo20141108FieldSpecified;
        
        private int fiz_liczbaJednLokalnychField;
        
        private bool fiz_liczbaJednLokalnychFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string fiz_regon9 {
            get {
                return this.fiz_regon9Field;
            }
            set {
                this.fiz_regon9Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string fiz_nip {
            get {
                return this.fiz_nipField;
            }
            set {
                this.fiz_nipField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public rootDaneFiz_statusNip fiz_statusNip {
            get {
                return this.fiz_statusNipField;
            }
            set {
                this.fiz_statusNipField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fiz_statusNipSpecified {
            get {
                return this.fiz_statusNipFieldSpecified;
            }
            set {
                this.fiz_statusNipFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string fiz_nazwisko {
            get {
                return this.fiz_nazwiskoField;
            }
            set {
                this.fiz_nazwiskoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string fiz_imie1 {
            get {
                return this.fiz_imie1Field;
            }
            set {
                this.fiz_imie1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string fiz_imie2 {
            get {
                return this.fiz_imie2Field;
            }
            set {
                this.fiz_imie2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string fiz_dataWpisuPodmiotuDoRegon {
            get {
                return this.fiz_dataWpisuPodmiotuDoRegonField;
            }
            set {
                this.fiz_dataWpisuPodmiotuDoRegonField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string fiz_dataZaistnieniaZmiany {
            get {
                return this.fiz_dataZaistnieniaZmianyField;
            }
            set {
                this.fiz_dataZaistnieniaZmianyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string fiz_dataSkresleniaPodmiotuZRegon {
            get {
                return this.fiz_dataSkresleniaPodmiotuZRegonField;
            }
            set {
                this.fiz_dataSkresleniaPodmiotuZRegonField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string fiz_podstawowaFormaPrawna_Symbol {
            get {
                return this.fiz_podstawowaFormaPrawna_SymbolField;
            }
            set {
                this.fiz_podstawowaFormaPrawna_SymbolField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string fiz_szczegolnaFormaPrawna_Symbol {
            get {
                return this.fiz_szczegolnaFormaPrawna_SymbolField;
            }
            set {
                this.fiz_szczegolnaFormaPrawna_SymbolField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string fiz_formaFinansowania_Symbol {
            get {
                return this.fiz_formaFinansowania_SymbolField;
            }
            set {
                this.fiz_formaFinansowania_SymbolField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string fiz_formaWlasnosci_Symbol {
            get {
                return this.fiz_formaWlasnosci_SymbolField;
            }
            set {
                this.fiz_formaWlasnosci_SymbolField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string fiz_podstawowaFormaPrawna_Nazwa {
            get {
                return this.fiz_podstawowaFormaPrawna_NazwaField;
            }
            set {
                this.fiz_podstawowaFormaPrawna_NazwaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string fiz_szczegolnaFormaPrawna_Nazwa {
            get {
                return this.fiz_szczegolnaFormaPrawna_NazwaField;
            }
            set {
                this.fiz_szczegolnaFormaPrawna_NazwaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string fiz_formaFinansowania_Nazwa {
            get {
                return this.fiz_formaFinansowania_NazwaField;
            }
            set {
                this.fiz_formaFinansowania_NazwaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string fiz_formaWlasnosci_Nazwa {
            get {
                return this.fiz_formaWlasnosci_NazwaField;
            }
            set {
                this.fiz_formaWlasnosci_NazwaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int fiz_dzialalnoscCeidg {
            get {
                return this.fiz_dzialalnoscCeidgField;
            }
            set {
                this.fiz_dzialalnoscCeidgField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fiz_dzialalnoscCeidgSpecified {
            get {
                return this.fiz_dzialalnoscCeidgFieldSpecified;
            }
            set {
                this.fiz_dzialalnoscCeidgFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int fiz_dzialalnoscRolnicza {
            get {
                return this.fiz_dzialalnoscRolniczaField;
            }
            set {
                this.fiz_dzialalnoscRolniczaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fiz_dzialalnoscRolniczaSpecified {
            get {
                return this.fiz_dzialalnoscRolniczaFieldSpecified;
            }
            set {
                this.fiz_dzialalnoscRolniczaFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int fiz_dzialalnoscPozostala {
            get {
                return this.fiz_dzialalnoscPozostalaField;
            }
            set {
                this.fiz_dzialalnoscPozostalaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fiz_dzialalnoscPozostalaSpecified {
            get {
                return this.fiz_dzialalnoscPozostalaFieldSpecified;
            }
            set {
                this.fiz_dzialalnoscPozostalaFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int fiz_dzialalnoscSkreslonaDo20141108 {
            get {
                return this.fiz_dzialalnoscSkreslonaDo20141108Field;
            }
            set {
                this.fiz_dzialalnoscSkreslonaDo20141108Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fiz_dzialalnoscSkreslonaDo20141108Specified {
            get {
                return this.fiz_dzialalnoscSkreslonaDo20141108FieldSpecified;
            }
            set {
                this.fiz_dzialalnoscSkreslonaDo20141108FieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int fiz_liczbaJednLokalnych {
            get {
                return this.fiz_liczbaJednLokalnychField;
            }
            set {
                this.fiz_liczbaJednLokalnychField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fiz_liczbaJednLokalnychSpecified {
            get {
                return this.fiz_liczbaJednLokalnychFieldSpecified;
            }
            set {
                this.fiz_liczbaJednLokalnychFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public enum rootDaneFiz_statusNip {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("")]
        Item,
        
        /// <remarks/>
        Uchylony,
        
        /// <remarks/>
        Unieważniony,
    }
}
