name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Install dot net tools
      run: npm install dotnettools
    - name: Bump version
      run: node ./node_modules/dotnettools/bin/dnt.js bump-versions patch
    - name: Add & Commit
      uses: EndBug/add-and-commit@v4.0.1
      with:
        message: Version update
    - name: Install dependencies
      run: dotnet restore ./src/Gus.Regon.BIR11.sln
    - name: Build
      run: dotnet build ./src/Gus.Regon.BIR11.sln --configuration Release --no-restore
    - name: Test
      run: dotnet test ./src/Gus.Regon.BIR11.sln --no-restore --verbosity normal
    - name: Publish NuGet
      uses: rohith/publish-nuget@v2.2.1
      with:
        PROJECT_FILE_PATH: ./src/Gus.Regon.BIR11.Proxy/Gus.Regon.BIR11.Proxy.csproj
        NUGET_KEY: ${{ secrets.GusNugetKey }}
